services:
  app:
    container_name: mywebapp
    image: dataripple-org/nginx-php82-fpm:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ".:/var/www/html:rw"
